//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from bf.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    using System;
    using System.Text;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IbfListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class bfBaseListener : IbfListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] bfParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] bfParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] bfParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] bfParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfPlus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListOfPlus([NotNull] bfParser.ListOfPlusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfPlus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListOfPlus([NotNull] bfParser.ListOfPlusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfMinus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListOfMinus([NotNull] bfParser.ListOfMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfMinus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListOfMinus([NotNull] bfParser.ListOfMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfLt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListOfLt([NotNull] bfParser.ListOfLtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfLt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListOfLt([NotNull] bfParser.ListOfLtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfGt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListOfGt([NotNull] bfParser.ListOfGtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfGt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListOfGt([NotNull] bfParser.ListOfGtContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
