//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from bf.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


    using System;
    using System.Text;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="bfParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IbfListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] bfParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] bfParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] bfParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] bfParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfPlus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListOfPlus([NotNull] bfParser.ListOfPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfPlus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListOfPlus([NotNull] bfParser.ListOfPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListOfMinus([NotNull] bfParser.ListOfMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfMinus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListOfMinus([NotNull] bfParser.ListOfMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfLt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListOfLt([NotNull] bfParser.ListOfLtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfLt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListOfLt([NotNull] bfParser.ListOfLtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="bfParser.listOfGt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListOfGt([NotNull] bfParser.ListOfGtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="bfParser.listOfGt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListOfGt([NotNull] bfParser.ListOfGtContext context);
}
